name: MatrixPipeline

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build_Stage
   jobs:

   - job: Build
     strategy:
       matrix:
         Python35:
           PYTHON_VERSION: '3.5'
         Python36:
           PYTHON_VERSION: '3.6.0'
         Python37:
           PYTHON_VERSION: '3.7'
       maxParallel: 2

     steps:
       - checkout: none
       - script: echo $(PYTHON_VERSION)