name: Solar System Workflow

on: 
  workflow_dispatch:
  push:

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v5

        - name: Welcome Message
          run: |
            echo "My first workflow"
            ls -ltra
            cat README.md

        - name: Executing Shell Script
          run: |
            chmod +x shell.sh
            ./shell.sh
  
